Add pyproject.toml for Custom Node Registry
digitaljohn/comfyui-propost pull request #23
Opened 2024-05-22 23:24 UTC by haohaocreates

We are building a global registry for custom nodes (similar to PyPI). The registry makes using custom nodes more reliable by reserving globally unique names for each custom node, and supporting semantic versioning.

Here’s some [more information](https://www.comfydocs.org/registry/overview#introduction) on the registry.

Action Required:

- [ ] Go to the [registry](https://www.comfyregistry.org/). Login and create a publisher id. Comment it here and we will update the PR (or just merge it and change it yourself).
- [ ] Write a short the description.
- [ ] Merge the separate Github Actions PR and run the workflow.
If you want to publish the node manually, [install the cli](https://www.comfydocs.org/comfy-cli/getting-started#install-cli) and run `comfy node publish`

Please message me on [Discord](https://discord.com/invite/comfycontrib) if you have any questions!

2024-06-30 01:31 UTC, haohaocreates commented
@digitaljohn, wondering if there's any way we can support you on this PR!

2024-06-30 15:02 UTC, digitaljohn requested changes

2024-06-30 15:02 UTC, digitaljohn commented on pyproject.toml
> +license = "LICENSE"
```suggestion
license = "MIT"
```

2024-07-02 15:28 UTC, haohaocreates commented
lgtm!

2024-07-02 20:45 UTC, digitaljohn commented
@haohaocreates just need #22 updated and merged then ill merge this in.

2024-07-31 14:19 UTC, haohaocreates commented
hey @digitaljohn , sorry about such a long delay, lmk if anything else I can support on!

2024-08-11 12:19 UTC, digitaljohn approved these changes

2024-08-11 12:20 UTC, merged